# ☪ Halal OS - Calamares Welcome Module Configuration
---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true
showDonateUrl:          true

requirements:
    requiredStorage:    15.0
    requiredRam:        2.0
    internetCheckUrl:   ""
    check:
        - storage
        - ram
        - power
    required:
        - storage
        - ram

geoip:
    style:  "none"
